# Generated by Django 3.2.5 on 2021-07-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='level',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
