# Generated by Django 3.2.5 on 2021-07-19 21:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0002_auto_20210718_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('level', models.SmallIntegerField(default=1)),
                ('coincidences', models.SmallIntegerField(default=2)),
                ('token', models.CharField(default='img', max_length=3)),
                ('victory_text', models.CharField(default='Ganaste!', max_length=100)),
                ('defeat_text', models.CharField(default='Perdiste!', max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='config',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
