# Generated by Django 3.2.5 on 2021-07-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210719_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=1)),
                ('coincidences', models.SmallIntegerField(default=2)),
                ('token', models.CharField(default='img', max_length=3)),
                ('victory_text', models.CharField(default='Ganaste!', max_length=100)),
                ('defeat_text', models.CharField(default='Perdiste!', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='coincidences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='defeat_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='victory_text',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='config',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='login.config'),
            preserve_default=False,
        ),
    ]
